
  export const requestorsData = [
  { "Requestor Name": "Abdhesh Tiwari", "Division": "EAM", "Client": "EKL" },
  { "Requestor Name": "Abhimanyu Prasad", "Division": "RED", "Client": "Sona" },
  { "Requestor Name": "Abhishek Dixit", "Division": "EAM", "Client": "EKL" },
  { "Requestor Name": "Abhishek Singh", "Division": "SIETZ", "Client": "SIETZ" },
  { "Requestor Name": "Aditi", "Division": "ECE", "Client": "EKL" },
  { "Requestor Name": "Amit Kumar Sagar", "Division": "RED", "Client": "Sona" },
  { "Requestor Name": "Anand Rawat", "Division": "ECE", "Client": "EKL" },
  { "Requestor Name": "Ashok Yadav", "Division": "RED", "Client": "Sona" },
  { "Requestor Name": "Ashu Garg", "Division": "EAM", "Client": "EKL" },
  { "Requestor Name": "Babita Sabarwal", "Division": "EAM", "Client": "EKL" },
  { "Requestor Name": "Chandan", "Division": "EKI", "Client": "EKL" },
  { "Requestor Name": "Dilip Singh", "Division": "TVTN", "Client": "TVTN" },
  { "Requestor Name": "Gaurav", "Division": "RED", "Client": "Sona" },
  { "Requestor Name": "Gautam", "Division": "RED", "Client": "Sona" },
  { "Requestor Name": "Gopal", "Division": "RED", "Client": "Sona" },
  { "Requestor Name": "Gulshan Bhambri", "Division": "SIETZ", "Client": "SIETZ" },
  { "Requestor Name": "Guramrit", "Division": "RED", "Client": "Sona" },
  { "Requestor Name": "Harshdeep Sodhi", "Division": "EAM", "Client": "EKL" },
  { "Requestor Name": "Harshita Sharma", "Division": "EAM", "Client": "EKL" },
  { "Requestor Name": "Jayant Singh", "Division": "EAM", "Client": "EKL" },
  { "Requestor Name": "Kamalaker", "Division": "EKI", "Client": "EKL" },
  { "Requestor Name": "Kapil Dev", "Division": "SNF Infra", "Client": "HCL" },
  { "Requestor Name": "Kiran Mahto", "Division": "EAM", "Client": "EKL" },
  { "Requestor Name": "Lucky Sharma", "Division": "EAM", "Client": "EKL" },
  { "Requestor Name": "Mamta Gupta", "Division": "TVTN", "Client": "TVTN" },
  { "Requestor Name": "Manish Kumar", "Division": "TVTN", "Client": "TVTN" },
  { "Requestor Name": "Mayank Pokhria", "Division": "RED", "Client": "Sona" },
  { "Requestor Name": "Mitesh Bauskar", "Division": "KAI", "Client": "EKL" },
  { "Requestor Name": "Mukesh Pal", "Division": "ECE", "Client": "EKL" },
  { "Requestor Name": "Munigopi M", "Division": "Syrma", "Client": "Syrma" },
  { "Requestor Name": "Nikhil Walecha", "Division": "TVTN", "Client": "TVTN" },
  { "Requestor Name": "Nilesh Shipalkar", "Division": "KAI", "Client": "EKL" },
  { "Requestor Name": "Nitesh Mishra", "Division": "EAM", "Client": "EKL" },
  { "Requestor Name": "Om Ravi Shankar", "Division": "EAM", "Client": "EKL" },
  { "Requestor Name": "Om Singh", "Division": "EAM", "Client": "EKL" },
  { "Requestor Name": "Poonam Patwal", "Division": "ECE", "Client": "EKL" },
  { "Requestor Name": "Pravesh Gumaste", "Division": "EAM", "Client": "EKL" },
  { "Requestor Name": "Prem Singh", "Division": "RED", "Client": "Sona" },
  { "Requestor Name": "Rahul Wadhwa", "Division": "RED", "Client": "Sona" },
  { "Requestor Name": "Rajeev Singh", "Division": "RED", "Client": "Sona" },
  { "Requestor Name": "Rajesh", "Division": "ECE", "Client": "EKL" },
  { "Requestor Name": "Shiyamsundar", "Division": "KAI", "Client": "EKL" },
  { "Requestor Name": "Sagar M", "Division": "EAM", "Client": "EKL" },
  { "Requestor Name": "Sahdev", "Division": "TVTN", "Client": "TVTN" },
  { "Requestor Name": "Sahil Rana", "Division": "RED", "Client": "Sona" },
  { "Requestor Name": "Sanjeev Kumar", "Division": "EAM", "Client": "EKL" },
  { "Requestor Name": "Sejal", "Division": "EAM", "Client": "EKL" },
  { "Requestor Name": "Shikhar Maurya", "Division": "KAI", "Client": "EKL" },
  { "Requestor Name": "Shubham Kumar", "Division": "SIETZ", "Client": "SIETZ" },
  { "Requestor Name": "Sirajuddin", "Division": "ECE", "Client": "EKL" },
  { "Requestor Name": "Sivan Perumal.K", "Division": "KAI", "Client": "EKL" },
  { "Requestor Name": "Sumit Pannu", "Division": "RED", "Client": "Sona" },
  { "Requestor Name": "Sutapa Guha", "Division": "RED", "Client": "Sona" },
  { "Requestor Name": "Suthakaran", "Division": "EAM", "Client": "EKL" },
  { "Requestor Name": "Tarun Chaprana", "Division": "EAM", "Client": "EKL" },
  { "Requestor Name": "Varun", "Division": "EAM", "Client": "EKL" },
  { "Requestor Name": "Vijay Sen Tripathi", "Division": "KAI", "Client": "EKL" },
  { "Requestor Name": "Vikram", "Division": "HT Media", "Client": "HT Media" },
  { "Requestor Name": "Vinay Nimesh", "Division": "RED", "Client": "Sona" },
  { "Requestor Name": "Yogesh", "Division": "EAM", "Client": "EKL" },
  { "Requestor Name": "Zahid Hussain", "Division": "Sona RED", "Client": "Sona" },
  { "Requestor Name": "Utkarsh Singh", "Division": "EAM", "Client": "EKL" },
  { "Requestor Name": "Abhishek Agarwal", "Division": "RED", "Client": "Sona" },
  { "Requestor Name": "Sanjay Soni", "Division": "RED", "Client": "Sona" },
  { "Requestor Name": "A. Rajkumar", "Division": "KAI", "Client": "EKL" },
  { "Requestor Name": "Vimal Kumar", "Division": "SIETZ", "Client": "SIETZ" },
  { "Requestor Name": "Rajkumar Sharma", "Division": "RED", "Client": "Sona" },
  { "Requestor Name": "Sasi Kumar", "Division": "KAI", "Client": "EKL" },
  { "Requestor Name": "Rohit Garg", "Division": "RED", "Client": "Sona" },
  { "Requestor Name": "Kranthi S", "Division": "EAM", "Client": "EKL" },
  { "Requestor Name": "Prashant", "Division": "RED", "Client": "Sona" },
  { "Requestor Name": "Rakesh Patnaik", "Division": "KAI", "Client": "EKL" },
  { "Requestor Name": "Sushil Bhise", "Division": "KAI", "Client": "EKL" },
  { "Requestor Name": "Rajat Sharma", "Division": "EAM", "Client": "EKL" },
  { "Requestor Name": "Shivam Kumar", "Division": "KAI", "Client": "EKL" },
  { "Requestor Name": "Namdev", "Division": "KAI", "Client": "EKL" },
  { "Requestor Name": "Meenakshi Ghai", "Division": "RED", "Client": "Sona" },
  { "Requestor Name": "Chetan Swaroop", "Division": "EAM", "Client": "EKL" }
];
